plugin/ryu/db/model: make OFPServer.address not primary_key
Since sqlite doesn't support multicolumn primary key, sqlalchmey fails
to create column of it. So make OFPSErver.address not primary_key.

======================================================================
ERROR: test_network_attachment_filter (quantum.tests.unit.test_api.APIFiltersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/quantum-root/quantum/tests/unit/test_api.py", line 150, in setUp
    test_api.ATTS: atts.ControllerV11._serialization_metadata})
  File "/quantum-root/quantum/tests/unit/_test_api.py", line 105, in setUp
    self.api = api_router_cls(options)
  File "/quantum-root/quantum/api/__init__.py", line 46, in __init__
    self._setup_routes(mapper, options)
  File "/quantum-root/quantum/api/__init__.py", line 53, in _setup_routes
    self._setup_base_routes(mapper, options, self._version)
  File "/quantum-root/quantum/api/__init__.py", line 60, in _setup_base_routes
    plugin = manager.QuantumManager.get_plugin(options)
  File "/quantum-root/quantum/manager.py", line 87, in get_plugin
    cls._instance = cls(options, config_file)
  File "/quantum-root/quantum/manager.py", line 82, in __init__
    self.plugin = plugin_klass()
  File "/quantum-root/quantum/plugins/ryu/ryu_quantum_plugin.py", line 120, in __init__
    self.driver = OFPRyuDriver(self.config)
  File "/quantum-root/quantum/plugins/ryu/ryu_quantum_plugin.py", line 49, in __init__
    ryu_db.set_ofp_servers(hosts)
  File "/quantum-root/quantum/plugins/ryu/db/api.py", line 36, in set_ofp_servers
    session.flush()
  File "/quantum-root/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1559, in flush
    self._flush(objects)
  File "/quantum-root/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1630, in _flush
    flush_context.execute()
  File "/quantum-root/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 331, in execute
    rec.execute(self)
  File "/quantum-root/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 475, in execute
    uow
  File "/quantum-root/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2291, in _save_obj
    execute(statement, params)
  File "/quantum-root/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in execute
    params)
  File "/quantum-root/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1538, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/quantum-root/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1646, in _execute_context
    context)
  File "/quantum-root/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_context
    context)
  File "/quantum-root/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 330, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) ofp_server.id may not be NULL u'INSERT INTO ofp_server (address, host_type) VALUES (?, ?)' ('172.16.3.33:6633', 'controller')
-------------------- >> begin captured logging << --------------------
quantum.manager: DEBUG: Plugin location:ryu_quantum_plugin.RyuQuantumPlugin
quantum.manager: DEBUG: Successfully imported Quantum plug-in.All compatibility tests passed
root: DEBUG: Using configuration file: /quantum-root/etc/quantum/plugins/ryu/ryu.ini
root: DEBUG: Config: <ConfigParser.ConfigParser instance at 0x22e09e0>
--------------------- >> end captured logging << ---------------------

Signed-off-by: Isaku Yamahata <yamahata@valinux.co.jp>