plugins/ryu/agent: fix exception
When starting up, the network is expected to be created by quantum server.
However there is a race between quantum server startup and quantum agent
startup. So have agent also make the network.

Traceback (most recent call last):
  File "/opt/stack/quantum/quantum/plugins/ryu/agent/ryu_quantum_agent.py", line 540, in <module>
    main()
  File "/opt/stack/quantum/quantum/plugins/ryu/agent/ryu_quantum_agent.py", line 534, in main
    plugin.daemon_loop()
  File "/opt/stack/quantum/quantum/plugins/ryu/agent/ryu_quantum_agent.py", line 490, in daemon_loop
    self.gre_ports.update()
  File "/opt/stack/quantum/quantum/plugins/ryu/agent/ryu_quantum_agent.py", line 367, in update
    self._add_port(node)
  File "/opt/stack/quantum/quantum/plugins/ryu/agent/ryu_quantum_agent.py", line 344, in _add_port
    self.int_br.datapath_id, ofport)
  File "/opt/stack/ryu/ryu/app/client.py", line 91, in create_port
    self._do_request('POST', self.path_port % (network_id, dpid, port))
  File "/opt/stack/ryu/ryu/app/client.py", line 55, in _do_request
    res.getheaders(), res.read())
httplib.HTTPException: (<httplib.HTTPResponse instance at 0x25e7a28>, 'code 404 reason Resource not found', [('date', 'Tue, 10 Apr 2012 02:26:03 GMT'), ('content-length', '466'), ('content-type', 'application/json')], '{"displayError": "The server does not have data for the request.", "error": "You submitted the following request.\\n\\n    POST /v1.0/networks/__NW_ID_VPORT_GRE__/00004e7f48e36243_\\n\\nThis request is not valid. The following paths were evaluated and failed\\nfor the indicated reason.\\n\\n    - /networks/{network-id}/{dpid}_{port-id}\\n      Invalid format: 00004e7f48e36243_\\n\\nYou can get a list of all valid requests with the following request.\\n\\n    GET /v1.0/doc"}')

Signed-off-by: Isaku Yamahata <yamahata@valinux.co.jp>